### ISSUE TITLE
Remove Prototype <= 1.6.1 Support

### ISSUE THREAD

**Issue by bnjmnt4n** [bestiejs/json3#66]
Prototype <= 1.6.1 support was added quite some time ago, in #8, back when many people were still using outdated versions of Prototype. However, the current Prototype version is 1.7.2 (released this year), and the toJSON bug was fixed in 1.7 (released in 2010).

However, if we intend to use a replacer function to serialise Dates (as in #65), it might be difficult to ensure that the toJSON property of Strings, Numbers, Arrays and Dates are not called. Thus, I would recommend we remove support for Prototype <= 1.6.1.

@kitcambridge what do you think?

**Comment by kitcambridge** [comment]
Also (noting for posterity)...folks who still need old Prototype support can keep using 3.x. If we find bugs affecting both 3.x and 4.x, we can always backport fixes; there's no mandate to upgrade.
