### ISSUE TITLE
Use `devDependencies` instead of `vendor`

### ISSUE THREAD

**Issue by bnjmnt4n** [bestiejs/json3#67]
@jdalton recently did this for the other @bestiejs projects, so I was wondering if this could be done for JSON3 as well. Also, this would help to reduce the size of downloads from GitHub, as well as git.

**Comment by d10** [comment]
Note: if we make `master` the default and `gh-pages` just contains the built site, we would have to remove the Travis CI build status, as `gh-pages` wouldn't have tests anymore, while `master` contains the latest dev changes and thus could have a failing status, which would be shown on the site.
