### ISSUE TITLE
Create a bower package

### ISSUE THREAD

**Issue by rcollette** [bestiejs/json3#77]
Self explanatory

**Comment by kitcambridge** [comment]
Try `bower install json3`. :grinning:

**Comment by rcollette** [comment]
That's odd.  I could have sworn I didn't see it in bower when I searched on it in the repository.  My fault.  Thank you.

**Comment by kiwenlau** [comment]
@kitcambridge It's so nice that you managed to support so many ways for installing json3.  How did you do it? I'm also developing a similar tool. But I'm confused.
